/**
 * Section-aware merge tests for stage-a-validation — Welle Q / Q6.
 *
 * Verifies that `mergeWithExisting` keeps the existing per-spec sections for
 * specs NOT in the new run, and replaces only the headline-row + spec-section
 * for specs that ARE in the run. This prevents the side-effect we hit in
 * 2026-05-06 where Q2-verify and Q4-measurement runs (each on 1 spec)
 * overwrote STAGE-A-RESULTS.md with single-spec content.
 */

import { describe, it, expect } from 'vitest';

import { mergeWithExisting } from '../../eval/stage-a-validation.js';

// Mock SpecPrediction shape — local to test (interface is internal).
interface SpecPrediction {
  spec: string;
  baselineRate: number;
  predictedRate: number;
  predictedLiftPp: number;
}

const EXISTING_MD = `# Stage-A Validation Results

> Empirical Stage-A coverage measured by running the full deterministic layer (Spectral OAS3-default + apiq-custom + Walkers + Domain-Knowledge) on each of the 4 specs and scoring against its reference target via Jaccard. Generated by \`scripts/spike/eval/stage-a-validation.ts\`.
>
> Compare against \`STAGE-A-PREDICTIONS.md\` (Phase-0-time hypothesis).

## Headline: measured vs predicted coverage

| Spec | Baseline (C-i) | Predicted post-Stage-A | **Measured (Jaccard)** | **Measured (Embedding)** | Delta vs predicted |
|---|---:|---:|---:|---:|---:|
| stripe-full | 37.9% | 82.8% | 62.1% (18/29) | **62.1% (18/29)** | -20.7pp |
| pagerduty-full | 21.7% | 90.9% | 30.4% (7/23) | **69.6% (16/23)** | -21.3pp |
| dnd5eapi | 28.6% | 85.7% | 35.7% (5/14) | **85.7% (12/14)** | +0.0pp |
| github-rest | 12.9% | 86.9% | 25.8% (8/31) | **64.5% (20/31)** | -22.4pp |

## stripe-full

Findings emitted by deterministic layer: **9513**

Per-layer breakdown:

| Layer | Findings |
|---|---:|
| Spectral (OAS3-default) | 1978 |

## pagerduty-full

Findings emitted by deterministic layer: **3896**

Per-layer breakdown:

| Layer | Findings |
|---|---:|
| Spectral (OAS3-default) | 1422 |

## dnd5eapi

Findings emitted by deterministic layer: **483**

Per-layer breakdown:

| Layer | Findings |
|---|---:|
| Spectral (OAS3-default) | 217 |

## github-rest

Findings emitted by deterministic layer: **21106**

Per-layer breakdown:

| Layer | Findings |
|---|---:|
| Spectral (OAS3-default) | 5853 |

## What Phase B measures next

1. Real Stage-A pre-pass + LLM Phase-1+2 on each spec → measure post-pre-pass coverage delta.
`;

function makeSpecResult(specName: string): unknown {
  // Minimal mock — enough fields for renderHeadlineRow + renderSpecSection.
  return {
    spec: specName,
    reference: { findings: [] },
    findings: [],
    perLayer: {
      'spectral-oas3-default': 999,
      'spectral-apiq-custom': 0,
      'walker-statistical': 0,
      'module-class': 0,
      'domain-knowledge': 0,
    },
    perDetector: { 'mock:detector': 1 },
    jaccard: {
      coveredRefs: 99,
      totalRefs: 99,
      coverageRate: 0.99,
      substantiveCoveredRefs: 99,
      substantiveTotalRefs: 99,
      substantiveCoverageRate: 0.99,
      pureSpectralCoveredRefs: 99,
      pureSpectralTotalRefs: 99,
      pureSpectralCoverageRate: 0.99,
      domainKnowledgeCoveredRefs: 0,
      domainKnowledgeTotalRefs: 0,
      domainKnowledgeCoverageRate: 0,
      llmOnlyCoveredRefs: 0,
      llmOnlyTotalRefs: 0,
      llmOnlyCoverageRate: 0,
      knowledgeBackedCoveredRefs: 0,
      knowledgeBackedTotalRefs: 0,
      knowledgeBackedCoverageRate: 0,
      perRef: [],
    },
    cluster: { uniqueClusters: 1, repetitionRate: 0 },
    embedding: null,
    durationMs: 1,
  };
}

describe('stage-a-validation mergeWithExisting (Q6)', () => {
  it('subset run on 1 spec keeps the other 3 specs intact', () => {
    // Update only stripe-full with a dummy "post-fix" coverage of 99.0%
    const newResults = [makeSpecResult('stripe-full')];
    const predictions = new Map<string, SpecPrediction>([
      ['stripe-full', { spec: 'stripe-full', baselineRate: 0.379, predictedRate: 0.828, predictedLiftPp: 44.9 }],
      ['pagerduty-full', { spec: 'pagerduty-full', baselineRate: 0.217, predictedRate: 0.909, predictedLiftPp: 69.2 }],
      ['dnd5eapi', { spec: 'dnd5eapi', baselineRate: 0.286, predictedRate: 0.857, predictedLiftPp: 57.1 }],
      ['github-rest', { spec: 'github-rest', baselineRate: 0.129, predictedRate: 0.869, predictedLiftPp: 74.0 }],
    ]);

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const merged = mergeWithExisting(newResults as any, EXISTING_MD, predictions);

    // The 3 not-targeted spec sections survive verbatim
    expect(merged).toContain('## pagerduty-full');
    expect(merged).toContain('Findings emitted by deterministic layer: **3896**');
    expect(merged).toContain('## dnd5eapi');
    expect(merged).toContain('Findings emitted by deterministic layer: **483**');
    expect(merged).toContain('## github-rest');
    expect(merged).toContain('Findings emitted by deterministic layer: **21106**');

    // The targeted spec is replaced — old "9513" findings count gone, new "999" perLayer count present
    expect(merged).not.toContain('Findings emitted by deterministic layer: **9513**');
    expect(merged).toContain('## stripe-full');
    expect(merged).toContain('| Spectral (OAS3-default) | 999 |');

    // Headline row for stripe-full reflects new 99.0% coverage
    const headlineLine = merged
      .split('\n')
      .find((l: string) => l.startsWith('| stripe-full |'));
    expect(headlineLine).toBeDefined();
    expect(headlineLine!).toContain('99.0%');

    // Other headline rows preserved
    const pagerdutyLine = merged
      .split('\n')
      .find((l: string) => l.startsWith('| pagerduty-full |'));
    expect(pagerdutyLine).toContain('30.4% (7/23)');

    // Tail section preserved
    expect(merged).toContain('## What Phase B measures next');
    expect(merged).toContain('1. Real Stage-A pre-pass');
  });

  it('subset run on 2 specs keeps the other 2 specs intact', () => {
    const newResults = [
      makeSpecResult('stripe-full'),
      makeSpecResult('github-rest'),
    ];
    const predictions = new Map<string, SpecPrediction>([
      ['stripe-full', { spec: 'stripe-full', baselineRate: 0.379, predictedRate: 0.828, predictedLiftPp: 44.9 }],
      ['github-rest', { spec: 'github-rest', baselineRate: 0.129, predictedRate: 0.869, predictedLiftPp: 74.0 }],
      ['pagerduty-full', { spec: 'pagerduty-full', baselineRate: 0.217, predictedRate: 0.909, predictedLiftPp: 69.2 }],
      ['dnd5eapi', { spec: 'dnd5eapi', baselineRate: 0.286, predictedRate: 0.857, predictedLiftPp: 57.1 }],
    ]);

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const merged = mergeWithExisting(newResults as any, EXISTING_MD, predictions);

    // pagerduty + dnd5eapi sections stay verbatim
    expect(merged).toContain('Findings emitted by deterministic layer: **3896**');
    expect(merged).toContain('Findings emitted by deterministic layer: **483**');

    // stripe + github-rest sections replaced (old finding-counts gone)
    expect(merged).not.toContain('Findings emitted by deterministic layer: **9513**');
    expect(merged).not.toContain('Findings emitted by deterministic layer: **21106**');
  });
});
